material = struct(...
    'qdeg', 0, ...
    'beg', 0, ...
    'r', 0, ...
    'eps', 0, ...
    'cost', 0, ...
    'tox', 0, ...
    'name', 'a' ...
    );
recipe = struct(...
    'ratios', [0,0], ...
    'mats', [mat1,mat2], ...
    'total', 0, ...
    'minUse', 0, ...
    'cost', 0, ...
    'tox', 0 ...
    );